### ISSUE TITLE
registerServey 오류

### ISSUE THREAD

**Issue by 404err-or** [331leo/hcskr_python#24]
```
Traceback (most recent call last):
    File "hcs.py", line 139, in selfcheck
        asyncSelfCheck(name, birth, area, schoolname, level, password, customloginname)
    File "/경로/asyncio/base_events.py", line 484, in run_until_complete
        return future.result()
    File "hcs.py", line 136, in asyncSelfCheck
        session=session,
    File "/경로/request.py", line 21, in send_hcsreq
        return await resp.json()
    File "/경로/aiohttp/client_reqrep.py", line 1103, in json
        headers=self.headers,
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/html;charset=utf-8', url=URL('https://genhcs.eduro.go.kr/registerServey')
```

해당 오류가 뜨길래
```
async with session.post(
    headers=headers,
    url=f"https://{school}hcs.eduro.go.kr{endpoint}",
    json=json,
    allow_redirects=False
) as resp:
    return await resp.json()
```
부분을 상단에
`import json as json_module` 후
```
async with session.post(
    headers=headers,
    url=f"https://{school}hcs.eduro.go.kr{endpoint}",
    json=json,
    allow_redirects=False
) as resp:
    a = await resp.text()
print(a)
print(json_module.loads(a))
return json_module.loads(a)
```
로 중간 결과를 확인해 본 결과 

```
<!DOCTYPE html>
<html lang="ko">
<head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>학생 건강상태 자가진단</title>
    <link
      rel="shortcut icon"
      href="https://rl6cz18qh.toastcdn.net/eduro/favicon.ico"
      type="image/x-icon"
    />
    <link rel="icon" href="https://rl6cz18qh.toastcdn.net/eduro/favicon.ico" type="image/x-icon" />
    <link rel="stylesheet" href="https://rl6cz18qh.toastcdn.net/eduro/css/common.css">
    <link rel="stylesheet" href="https://rl6cz18qh.toastcdn.net/eduro/css/layer.css">
</head>
<body>
        <div id="softBoardListLayer">
                <div class="layerTitle">
                        <strong>에러가 발생했습니.</strong>

                </div>
                <p class="ex_star"><span class="color_red">&#42;</span>
                  사이트 돌아가기 <a href="https://hcs.eduro.go.kr">https://hcs.eduro.go.kr</a>
                </p>
        </div>
</body>
</html>
```
라는 결과가 나옵니다.
제 컴퓨터(python 3.9.6)에서 돌렸을 때에는 잘 돌아가는 반면, 학교 서버(python 3.6.8)에 업로드 했을 경우 위와 같은 오류가 발생합니다. 해결 방법이 있을까요..? 다른 부분은 다 잘 작동하지만, 이 부분에서만 오류가 발생합니다. 학교 서버를 제 마음대로 쓰지 못하기 때문에 python을 업데이트 할 수 없는 상황입니다..

**Comment by penggin** [comment]
https://github.com/331leo/hcskr_python/pull/15#issuecomment-886160602
파이썬을 업데이트 하는 방법외엔 방법이 없어보입니다.
