### ISSUE TITLE
자가진단 및 토큰제작중 오류 발생

### ISSUE THREAD

**Issue by selfdestruct404** [331leo/hcskr_python#26]
자가진단이나 토큰제작시 아래와 같은 오류가 발생하며 정상적으로 사용할 수 없습니다.

라즈베리 파이를 사용중이며 hcskr모듈을 업그레이드 했으며 파이썬 또한 3.8.0버전을 사용중 입니다.
필요하시다면 라즈베리파이로 해당 문제를 확인하실 수 있으십니다. 

```
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.8/site-packages/aiohttp/connector.py", line 969, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore  # noqa
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 1042, in create_connection
    transport, protocol = await self._create_connection_transport(
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 1072, in _create_connection_transport
    await waiter
  File "/usr/local/lib/python3.8/asyncio/selector_events.py", line 836, in _read_ready__data_received
    data = self._sock.recv(self.max_size)
ConnectionResetError: [Errno 104] Connection reset by peer

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "yhmonly.py", line 2, in <module>
    hcskr.selfcheck("개인정보 삭제")
  File "/home/pi/.local/lib/python3.8/site-packages/hcskr/hcs.py", line 24, in selfcheck
    return loop.run_until_complete(
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 608, in run_until_complete
    return future.result()
  File "/home/pi/.local/lib/python3.8/site-packages/hcskr/hcs.py", line 91, in asyncSelfCheck
    login_result = await asyncUserLogin(
  File "/home/pi/.local/lib/python3.8/site-packages/hcskr/hcs.py", line 232, in asyncUserLogin
    school_infos = await search_school(
  File "/home/pi/.local/lib/python3.8/site-packages/hcskr/request.py", line 32, in search_school
    async with session.get(
  File "/home/pi/.local/lib/python3.8/site-packages/aiohttp/client.py", line 1117, in __aenter__
    self._resp = await self._coro
  File "/home/pi/.local/lib/python3.8/site-packages/aiohttp/client.py", line 520, in _request
    conn = await self._connector.connect(
  File "/home/pi/.local/lib/python3.8/site-packages/aiohttp/connector.py", line 535, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/home/pi/.local/lib/python3.8/site-packages/aiohttp/connector.py", line 892, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/home/pi/.local/lib/python3.8/site-packages/aiohttp/connector.py", line 1051, in _create_direct_connection
    raise last_exc
  File "/home/pi/.local/lib/python3.8/site-packages/aiohttp/connector.py", line 1020, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "/home/pi/.local/lib/python3.8/site-packages/aiohttp/connector.py", line 975, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host hcs.eduro.go.kr:443 ssl:default [Connection reset by peer]

```

**Comment by selfdestruct404** [comment]
Python 3.9.6에서도 이슈가 발생합니다

**Comment by penggin** [comment]
자가진단 서버와 통신하는 모든곳에서 해당 오류가 발생하는것 같습니다. 또 뭘 바꾼것같네요..

**Comment by selfdestruct404** [comment]
저희 집 인터넷 문제였던것 같습니다. 오늘은 정상적으로 작동 하는걸로 보아 저때 인터넷 최대 이용량을 초과하여 인터넷 속도가 줄어든게 원인인거 같습니다. 제대로 확인 하지 않고 이슈로 올린점 죄송합니다!
